name: Provision EC2 with Dagger

on:
  workflow_dispatch:

jobs:
  provision-ec2:
    name: Run Dagger EC2 Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dagger and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dagger-io

      - name: Run Dagger pipeline to provision EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_VPC_ID: ${{ secrets.TF_VAR_VPC_ID }}
          TF_VAR_SUBNET_ID: ${{ secrets.TF_VAR_SUBNET_ID }}
          TF_VAR_SSH_PUBLIC_KEY: ${{ secrets.TF_VAR_SSH_PUBLIC_KEY }}

        run: python AppAWSDeploy/dagger_ec2_provision.py
