
name: Deploy Nitric FastAPI App

on:
  workflow_dispatch:

jobs:
  deploy-nitric-app:
    name: Deploy Nitric App on EC2 via Dagger
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dagger and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dagger-io>=0.18.0

      - name: Run Nitric Deploy via Dagger
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: python AppAWSDeploy/dagger_nitric_deploy.py
