name: Setup EC2 for Nitric Deployment

on:
  workflow_dispatch: # Allows manually triggering the workflow from the GitHub Actions UI
  push:
    branches:
      - main # Automatically triggers the workflow when code is pushed to the `main` branch

jobs:
  ec2-setup: # Job name responsible for configuring the EC2 instance
    runs-on: ubuntu-latest # GitHub's hosted runner with Ubuntu environment

    env:
      EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }} # Public IP of EC2 (set in GitHub Secrets)
      EC2_SSH_USER: ${{ secrets.EC2_SSH_USER }} # SSH username (e.g., ubuntu)
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }} # Base64-encoded private key

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 # Gets repo content

      - name: Set up SSH private key from base64
        run: |
          mkdir -p ~/.ssh
          echo "${EC2_SSH_PRIVATE_KEY}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$EC2_PUBLIC_IP" >> ~/.ssh/known_hosts

      - name: Install Python dependencies
        run: pip install dagger-io

      - name: Run EC2 setup pipeline
        run: |
          python AppAWSDeploy/dagger_EC2_prereq_setup.py
